
import { Meal, Order, UserProfile, OrderItem } from './types';
export * from './types';

export const MEALS: Meal[] = [
    {
        id: '1',
        name: 'Masala Dosa',
        category: 'Breakfast',
        price: 60,
        description: 'Crispy rice crepe served with coconut chutney and potato masala.',
        available: true,
        prepTime: 15,
    },
    {
        id: '2',
        name: 'Idli Sambar',
        category: 'Breakfast',
        price: 40,
        description: 'Steamed rice cakes served with lentil soup and chutney.',
        available: true,
        prepTime: 10,
    },
    {
        id: '3',
        name: 'Veg Thali',
        category: 'Lunch',
        price: 120,
        description: 'Complete meal with rice, roti, dal, vegetable curry, curd, and papad.',
        available: true,
        prepTime: 20,
    },
    {
        id: '5',
        name: 'Samosa',
        category: 'Snacks',
        price: 20,
        description: 'Fried pastry with a savory filling of spiced potatoes and peas.',
        available: true,
        prepTime: 5,
    },
    {
        id: '6',
        name: 'Cold Coffee',
        category: 'Snacks',
        price: 50,
        description: 'Chilled coffee blended with ice cream and chocolate syrup.',
        available: true,
        prepTime: 5,
    },
    {
        id: '8',
        name: 'Paneer Tikka',
        category: 'Snacks',
        price: 180,
        description: 'Grilled cottage cheese cubes marinated in spices.',
        available: true,
        prepTime: 20,
    },
    {
        id: '9',
        name: 'Hakka Noodles',
        category: 'Dinner',
        price: 140,
        description: 'Stir-fried noodles cooked with fresh vegetables.',
        available: true,
        prepTime: 15,
    },
    {
        id: '10',
        name: 'Pav Bhaji',
        category: 'Snacks',
        price: 110,
        description: 'Spiced vegetable mash served with buttery bread rolls.',
        available: true,
        prepTime: 15,
    },
    {
        id: '11',
        name: 'Chole Bhature',
        category: 'Lunch',
        price: 130,
        description: 'Spicy chickpea curry served with fried fluffy bread.',
        available: true,
        prepTime: 20,
    },
    {
        id: '12',
        name: 'Veg Sandwich',
        category: 'Breakfast',
        price: 80,
        description: 'Grilled sandwich with cucumber, tomato, and cheese.',
        available: true,
        prepTime: 10,
    },
    {
        id: '13',
        name: 'Mango Lassi',
        category: 'Snacks',
        price: 70,
        description: 'Sweet and refreshing yogurt drink with mango pulp.',
        available: true,
        prepTime: 5,
    },
    {
        id: '14',
        name: 'Gulab Jamun',
        category: 'Snacks',
        price: 60,
        description: 'Soft fried milk dumplings soaked in sugar syrup.',
        available: true,
        prepTime: 0,
    },
    {
        id: '15',
        name: 'Margherita Pizza',
        category: 'Dinner',
        price: 250,
        description: 'Classic pizza topped with tomato sauce and mozzarella cheese.',
        available: true,
        prepTime: 20,
    },
    {
        id: '16',
        name: 'Aloo Paratha',
        category: 'Breakfast',
        price: 90,
        description: 'Wheat flatbread stuffed with spiced mashed potatoes.',
        available: true,
        prepTime: 15,
    },
    {
        id: '17',
        name: 'Rajma Chawal',
        category: 'Lunch',
        price: 110,
        description: 'Red kidney bean curry served with steamed rice.',
        available: true,
        prepTime: 15,
    },
    {
        id: '18',
        name: 'Veg Burger',
        category: 'Snacks',
        price: 95,
        description: 'Burger with a crispy vegetable patty and fresh lettuce.',
        available: true,
        prepTime: 15,
    },
    {
        id: '19',
        name: 'French Fries',
        category: 'Snacks',
        price: 80,
        description: 'Crispy golden fried potato strips seasoned with salt.',
        available: true,
        prepTime: 10,
    },
    {
        id: '20',
        name: 'Veg Fried Rice',
        category: 'Dinner',
        price: 130,
        description: 'Rice stir-fried with mixed vegetables and mild spices.',
        available: true,
        prepTime: 15,
    },
    {
        id: '21',
        name: 'Pasta Arrabbiata',
        category: 'Dinner',
        price: 160,
        description: 'Pasta tossed in a spicy garlic and tomato sauce.',
        available: true,
        prepTime: 20,
    },
];

export const ORDERS: Order[] = [
    {
        id: 'ORD-001',
        date: '2023-10-25T12:30:00Z',
        items: [
            { mealId: '3', name: 'Veg Thali', quantity: 1, price: 120 },
            { mealId: '6', name: 'Cold Coffee', quantity: 1, price: 50 },
        ],
        total: 170,
        status: 'Picked Up',
    },
    {
        id: 'ORD-002',
        date: '2023-10-26T09:15:00Z',
        items: [
            { mealId: '1', name: 'Masala Dosa', quantity: 2, price: 60 },
        ],
        total: 120,
        status: 'Picked Up',
    },
];

export const USER_PROFILE: UserProfile = {
    id: 'SAP123456',
    name: 'Guest User',
    email: 'rahul.s@university.edu',
    phone: '+91 98765 43210',
    photoUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?q=80&w=2574&auto=format&fit=crop',
    loyaltyPoints: 750,
    tier: 'Silver',
};




// (End of file)

