import { CustomButton } from '../components/CustomButton';
import { IconSymbol } from '../components/ui/icon-symbol';
import { Colors, Spacing, BorderRadius, Shadows } from '../constants/theme';
import { useCart } from '../context/CartContext';
import { useAuth } from '../context/AuthContext';
import { useRouter, useLocalSearchParams } from 'expo-router';
import React, { useState, useEffect } from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View, Platform, TextInput, Modal, Switch } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Storage, KEYS } from '../services/storage';

// ... imports

export default function CheckoutScreen() {
    const router = useRouter();
    const params = useLocalSearchParams();
    const { items, total, count, clearCart, activeOffer } = useCart(); // Added activeOffer
    const { addLoyaltyPoints, user, placeOrder } = useAuth();

    const [isProcessing, setIsProcessing] = useState(false);
    const [upiId, setUpiId] = useState('');
    const [saveUpi, setSaveUpi] = useState(false);
    const [showSuccess, setShowSuccess] = useState(false);
    const [orderId, setOrderId] = useState('');
    const [pointsEarned, setPointsEarned] = useState(0);
    const [usePoints, setUsePoints] = useState(false);

    const pickupTime = params.pickupTime as string;

    // Calculate Discount
    let discount = 0;
    if (activeOffer) {
        if (activeOffer.id === '1') { // 20% OFF up to ₹150
            discount = Math.min(total * 0.2, 150);
        } else if (activeOffer.id === '2') { // Free Coffee
            // Find coffee item? Or flat amount? Let's assume flat 50 for now or find item
            const coffee = items.find(i => i.name.toLowerCase().includes('coffee'));
            if (coffee) discount = coffee.price;
        } else if (activeOffer.id === '3') { // Flat 50
            discount = 50;
        } else if (activeOffer.id === '4') { // BOGO
            // Find most expensive beverage? Simplify to 50 for demo
            discount = 50;
        } else if (activeOffer.id === '5') { // Free Dessert
            discount = 50; // Simplify
        }
    }

    // Ensure discount doesn't exceed total
    discount = Math.min(discount, total);

    const subtotal = total - discount;
    const taxes = subtotal * 0.05;
    const initialTotal = subtotal + taxes;

    // Use Loyalty Points (1 point = ₹1)
    const maxPointsAvailable = user?.loyaltyPoints || 0;
    const pointsToUse = usePoints ? Math.min(maxPointsAvailable, initialTotal) : 0;
    const grandTotal = initialTotal - pointsToUse;

    useEffect(() => {
        const loadSavedUpi = async () => {
            const saved = await Storage.getItem(KEYS.SAVED_UPI);
            if (saved) {
                setUpiId(saved);
                setSaveUpi(true);
            }
        };
        loadSavedUpi();
    }, []);

    const handleBack = () => {
        router.back();
    };

    const handlePlaceOrder = async () => {
        if (!upiId.trim()) {
            Alert.alert('Required', 'Please enter your UPI ID');
            return;
        }
        if (!upiId.includes('@')) {
            Alert.alert('Invalid ID', 'Please enter a valid UPI ID (e.g., user@upi)');
            return;
        }

        setIsProcessing(true);

        try {
            // Create Order Object
            const orderDetails = {
                // ID will be generated by backend
                date: new Date().toISOString(),
                status: 'Placed',
                items: items.map(item => ({
                    mealId: item.id,
                    name: item.name,
                    quantity: item.quantity,
                    price: item.price
                })),
                total: initialTotal, // Original total before points
                pointsUsed: pointsToUse,
                paymentMethod: 'UPI',
                pickupTime: pickupTime // Added missing field
            };

            await placeOrder(orderDetails);

            // Fetch the latest order to show its ID (placeOrder updates orders list)
            // Or simpler: just use a placeholder since we don't get the ID back from placeOrder easily without refactoring context
            // actually placeOrder implementation in AuthContext doesn't return the order ID to the caller. 
            // We can modify AuthContext or just rely on the order list update.
            // For now, let's keep the user experience smooth. 

            // Note: In a real app we would want placeOrder to return the created order object.
            // Since I can't easily change AuthContext signature without checking all usages, 
            // I'll stick to using a generic success message or the random ID if needed, 
            // but wait, the previous code generated a random ID 'QPO-...'.
            // The backend generates 'ORD-...'.
            // Let's rely on success for now.

            const points = Math.floor(grandTotal * 0.05);
            setPointsEarned(points);
            // Points are updated via placeOrder backend refresh

            setShowSuccess(true);

            // Save UPI if checked
            if (saveUpi) {
                await Storage.setItem(KEYS.SAVED_UPI, upiId);
            }

            clearCart();
        } catch (error: any) {
            console.error(error);
            Alert.alert('Order Failed', error.message || 'Something went wrong. Please try again.');
        } finally {
            setIsProcessing(false);
        }
    };

    const handleSuccessClose = () => {
        setShowSuccess(false);
        router.replace('/(tabs)');
    };

    return (
        <SafeAreaView style={styles.container}>
            <View style={styles.header}>
                <TouchableOpacity onPress={handleBack} style={styles.backButton}>
                    <IconSymbol name="chevron.left" size={28} color={Colors.light.text} />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Checkout</Text>
                <View style={{ width: 40 }} />
            </View>

            <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
                {/* Order Summary */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Order Summary</Text>
                    <View style={styles.card}>
                        {items.map((item) => (
                            <View key={item.id} style={styles.itemRow}>
                                <View style={styles.itemInfo}>
                                    <View style={styles.itemBadge}>
                                        <Text style={styles.itemQuantity}>{item.quantity}x</Text>
                                    </View>
                                    <Text style={styles.itemName}>{item.name}</Text>
                                </View>
                                <Text style={styles.itemPrice}>₹{item.price * item.quantity}</Text>
                            </View>
                        ))}
                    </View>
                </View>

                {/* Bill Details */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Bill Details</Text>
                    <View style={styles.card}>
                        <View style={styles.billRow}>
                            <Text style={styles.billLabel}>Item Total</Text>
                            <Text style={styles.billValue}>₹{total}</Text>
                        </View>
                        {activeOffer && (
                            <View style={styles.billRow}>
                                <Text style={[styles.billLabel, { color: Colors.light.success }]}>Discount ({activeOffer.title})</Text>
                                <Text style={[styles.billValue, { color: Colors.light.success }]}>-₹{discount.toFixed(2)}</Text>
                            </View>
                        )}
                        <View style={styles.billRow}>
                            <Text style={styles.billLabel}>Taxes & Charges (5%)</Text>
                            <Text style={styles.billValue}>₹{taxes.toFixed(2)}</Text>
                        </View>
                        {pointsToUse > 0 && (
                            <View style={styles.billRow}>
                                <Text style={[styles.billLabel, { color: Colors.light.primary }]}>Loyalty Points Used</Text>
                                <Text style={[styles.billValue, { color: Colors.light.primary }]}>-₹{pointsToUse.toFixed(2)}</Text>
                            </View>
                        )}
                        <View style={styles.divider} />
                        <View style={styles.billRow}>
                            <Text style={styles.grandTotalLabel}>Grand Total</Text>
                            <Text style={styles.grandTotalValue}>₹{grandTotal.toFixed(2)}</Text>
                        </View>
                    </View>
                </View>

                {/* Loyalty Points Section */}
                {(user?.loyaltyPoints || 0) > 0 && (
                    <View style={styles.section}>
                        <Text style={styles.sectionTitle}>Loyalty Points</Text>
                        <View style={[styles.card, usePoints && styles.pointsActiveCard]}>
                            <View style={styles.pointsHeader}>
                                <View style={{ flex: 1 }}>
                                    <Text style={styles.pointsBalanceLabel}>Available: {user?.loyaltyPoints} points</Text>
                                    <Text style={styles.pointsValueLabel}>1 point = ₹1</Text>
                                </View>
                                <Switch
                                    value={usePoints}
                                    onValueChange={setUsePoints}
                                    trackColor={{ false: '#d1d1d1', true: Colors.light.primary }}
                                />
                            </View>
                            {usePoints && (
                                <Text style={styles.pointsSuccessText}>
                                    Using {pointsToUse.toFixed(0)} points to save ₹{pointsToUse.toFixed(0)}
                                </Text>
                            )}
                        </View>
                    </View>
                )}

                {/* Pickup Details */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Pickup Details</Text>
                    <View style={styles.card}>
                        <View style={styles.billRow}>
                            <Text style={styles.billLabel}>Pickup Time</Text>
                            <Text style={styles.billValue}>{pickupTime || 'Not scheduled'}</Text>
                        </View>
                    </View>
                </View>

                {/* Payment Method */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Payment Method</Text>
                    <View style={[styles.card, styles.paymentCard]}>
                        <View style={styles.paymentRow}>
                            <View style={styles.radioSelected} />
                            <Text style={styles.paymentText}>UPI</Text>
                        </View>
                        <Text style={styles.paymentSubtext}>Pay via Google Pay, PhonePe, Paytm</Text>

                        <View style={styles.divider} />

                        <Text style={styles.inputLabel}>Enter UPI ID</Text>
                        <TextInput
                            style={styles.input}
                            placeholder="e.g. 9876543210@upi"
                            value={upiId}
                            onChangeText={setUpiId}
                            autoCapitalize="none"
                            keyboardType="email-address"
                        />

                        <View style={styles.checkboxRow}>
                            <Switch
                                value={saveUpi}
                                onValueChange={setSaveUpi}
                                trackColor={{ false: '#d1d1d1', true: Colors.light.secondary }}
                                thumbColor={saveUpi ? Colors.light.primary : '#f4f3f4'}
                            />
                            <Text style={styles.checkboxLabel}>Save UPI ID for future payments</Text>
                        </View>
                    </View>
                </View>
            </ScrollView>

            <View style={styles.footer}>
                <View style={styles.totalContainer}>
                    <Text style={styles.totalLabel}>Total to Pay</Text>
                    <Text style={styles.totalAmount}>₹{grandTotal.toFixed(2)}</Text>
                </View>
                <TouchableOpacity
                    style={[styles.payButton, isProcessing && { opacity: 0.7 }]}
                    onPress={handlePlaceOrder}
                    disabled={isProcessing}
                >
                    <Text style={styles.payButtonText}>{isProcessing ? 'Processing...' : 'Pay & Order'}</Text>
                </TouchableOpacity>
            </View>

            {/* Success Modal */}
            <Modal
                visible={showSuccess}
                transparent
                animationType="fade"
                onRequestClose={() => { }} // Prevent hardware back
            >
                <View style={styles.modalOverlay}>
                    <View style={styles.modalContent}>
                        <View style={styles.successIconCircle}>
                            <IconSymbol name="checkmark" size={40} color="#FFF" />
                        </View>
                        <Text style={styles.successTitle}>Payment Successful!</Text>
                        <Text style={styles.successMessage}>
                            Your order has been placed successfully.
                        </Text>

                        <View style={styles.pointsContainer}>
                            <Text style={styles.pointsLabel}>You Earned</Text>
                            <Text style={styles.pointsValue}>+{pointsEarned} Points</Text>
                        </View>

                        <View style={styles.orderIdContainer}>
                            <Text style={styles.orderIdLabel}>Order ID</Text>
                            <Text style={styles.orderIdValue}>{orderId}</Text>
                        </View>
                        <TouchableOpacity style={styles.homeButton} onPress={handleSuccessClose}>
                            <Text style={styles.homeButtonText}>Back to Home</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </Modal>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.md,
        backgroundColor: Colors.light.background,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.border,
    },
    backButton: {
        padding: Spacing.sm,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Colors.light.text,
    },
    content: {
        padding: Spacing.md,
        paddingBottom: 100,
    },
    section: {
        marginBottom: Spacing.lg,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: Colors.light.text,
        marginBottom: Spacing.sm,
        marginLeft: Spacing.xs,
    },
    card: {
        backgroundColor: Colors.light.surface,
        borderRadius: BorderRadius.md,
        padding: Spacing.md,
        ...Shadows.light.small,
    },
    itemRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Spacing.sm,
    },
    itemInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    itemBadge: {
        backgroundColor: Colors.light.surfaceHighlight,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: BorderRadius.sm,
        marginRight: Spacing.sm,
        borderWidth: 1,
        borderColor: Colors.light.border,
    },
    itemQuantity: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.light.primary,
    },
    itemName: {
        fontSize: 16,
        color: Colors.light.text,
    },
    itemPrice: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.light.text,
    },
    billRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: Spacing.xs,
    },
    billLabel: {
        fontSize: 14,
        color: Colors.light.textSecondary,
    },
    billValue: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.light.text,
    },
    divider: {
        height: 1,
        backgroundColor: Colors.light.border,
        marginVertical: Spacing.sm,
    },
    grandTotalLabel: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.light.text,
    },
    grandTotalValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.light.primary,
    },
    paymentCard: {
        borderWidth: 1,
        borderColor: Colors.light.primary,
        backgroundColor: '#F0FFFA', // Light teal tint
    },
    paymentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    radioSelected: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 5,
        borderColor: Colors.light.primary,
        marginRight: Spacing.sm,
        backgroundColor: '#FFF',
    },
    paymentText: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.light.text,
    },
    paymentSubtext: {
        fontSize: 12,
        color: Colors.light.textSecondary,
        marginLeft: 26, // Align with text
        marginBottom: Spacing.md,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.light.text,
        marginBottom: 6,
    },
    input: {
        backgroundColor: '#FFF',
        borderWidth: 1,
        borderColor: Colors.light.border,
        borderRadius: BorderRadius.sm,
        padding: 10,
        fontSize: 16,
        marginBottom: Spacing.md,
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    checkboxLabel: {
        marginLeft: Spacing.sm,
        fontSize: 14,
        color: Colors.light.text,
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: Colors.light.background,
        padding: Spacing.md,
        borderTopWidth: 1,
        borderTopColor: Colors.light.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        ...Shadows.light.medium,
    },
    totalContainer: {

    },
    totalLabel: {
        fontSize: 12,
        color: Colors.light.textSecondary,
    },
    totalAmount: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Colors.light.text,
    },
    payButton: {
        backgroundColor: Colors.light.success,
        paddingVertical: 12,
        paddingHorizontal: Spacing.xl,
        borderRadius: BorderRadius.md,
    },
    payButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: Spacing.xl,
    },
    modalContent: {
        backgroundColor: '#FFF',
        borderRadius: BorderRadius.lg,
        padding: Spacing.xl,
        alignItems: 'center',
        width: '100%',
        maxWidth: 340,
        ...Shadows.light.medium,
    },
    successIconCircle: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: Colors.light.success,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: Spacing.md,
    },
    successTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: Colors.light.text,
        marginBottom: Spacing.sm,
    },
    successMessage: {
        fontSize: 16,
        color: Colors.light.textSecondary,
        textAlign: 'center',
        marginBottom: Spacing.md,
    },
    pointsContainer: {
        alignItems: 'center',
        marginBottom: Spacing.lg,
        backgroundColor: '#FFF8E1', // Light gold/yellow background
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: BorderRadius.circle,
        borderWidth: 1,
        borderColor: '#FFD700',
    },
    pointsLabel: {
        fontSize: 12,
        color: '#BDB76B', // Dark khaki
        textTransform: 'uppercase',
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    pointsValue: {
        fontSize: 18,
        fontWeight: '900',
        color: '#DAA520', // GoldenRod
    },
    orderIdContainer: {
        backgroundColor: Colors.light.surface,
        padding: Spacing.md,
        borderRadius: BorderRadius.md,
        width: '100%',
        alignItems: 'center',
        marginBottom: Spacing.lg,
    },
    orderIdLabel: {
        fontSize: 12,
        color: Colors.light.textSecondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    orderIdValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.light.primary,
        marginTop: 4,
    },
    homeButton: {
        backgroundColor: Colors.light.primary,
        paddingVertical: 12,
        paddingHorizontal: Spacing.xl,
        borderRadius: BorderRadius.circle,
        width: '100%',
        alignItems: 'center',
    },
    homeButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    pointsActiveCard: {
        borderColor: Colors.light.primary,
        borderWidth: 1.5,
        backgroundColor: '#F0FFFA',
    },
    pointsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    pointsBalanceLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.light.text,
    },
    pointsValueLabel: {
        fontSize: 12,
        color: Colors.light.textSecondary,
        marginTop: 2,
    },
    pointsSuccessText: {
        marginTop: Spacing.sm,
        fontSize: 14,
        color: Colors.light.primary,
        fontWeight: '600',
    },
});
